### ISSUE TITLE
Ark Flatpak does not provide Dolphin context menu action to extract and to compress files

### ISSUE THREAD

**Issue by DenysMb** [flathub/org.kde.dolphin#139]
I opened this bug here (https://bugs.kde.org/show_bug.cgi?id=463240) and I was answered to report this issue here.

The Flatpak version of Ark does not provide Dolphin context menu action to extract or compress files.

In additional commets I wrote:
> A possible easy and quick solution (for the Flatpak version) could be do as was done before on Ark 16.04 and provide the .desktop files of the services menu on $HOME/.local/share/flatpak/exports/share/kservices5/ServiceMenus/
The two files provided were: ark_addtoservicemenu.desktop and ark_servicemenu.desktop
All we need to do is change "ark" to "flatpak run org.kde.ark" on the Exec commands.

But I don't know if this is actually possible.

Nate Graham later add a comment where he said this:

> For now, the only thing we could do is embed Ark's context menu functionality inside of Dolphin's Flatpak build, so that you always have it in Dolphin even if Ark isn't installed.

**Comment by travier** [comment]
We already include Ark in the Dolphin Flatpak. I don't understand your issue.

**Comment by DenysMb** [comment]
> We already include Ark in the Dolphin Flatpak. I don't understand your issue.

Sorry for the delay. I mean the integration between Ark Flatpak and Dolphin Non-Flatpak.

**Comment by travier** [comment]
This is https://bugs.kde.org/show_bug.cgi?id=463240#c4

It's hard to do.

**Comment by travier** [comment]
I'm going to close this issue as it's not going to happen here. It would need a clearer bug report being filed in KDE.
