### ISSUE TITLE
Dolphin is unable to read some folders

### ISSUE THREAD

**Issue by RacerBG** [flathub/org.kde.dolphin#200]
**Step to reproduce**

Run Dolphin and try to access some of the system folders.

**Actual result**

The flatpak version of Konsole sees the following folders in "/": bin  boot  dev  etc  home  initrd.img  initrd.img.old  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  vmlinuz  vmlinuz.old
The flatpak version of Dolphin sees the following folders in "/": app bin dev etc home lib lib64 media proc run sbin sys tmp usr var

Giving additional permissions from Flatseal to Dolphin does not solve this problem. Also I have no idea what is this app folder which Dolphin sees and Konsole does not...

**Expected result**

Konsole and Dolphin should show the same result for every folder in the file system.

**Version**

Flatpak 1.14.4
Dolphin 23.08.4
Konsole 23.08.4

**Comment by travier** [comment]
Documenting that in https://github.com/flathub/org.kde.dolphin/pull/259.

Konsole has access to everything because it spawns the shell outside the sandbox.
