### ISSUE TITLE
Add `--socket=pulseaudio` to enable audio and video file preview

### ISSUE THREAD

**Issue by freecicero** [flathub/org.kde.dolphin#34]
I am still working with Dolphin previews, this time trying to get sound to work, which it currently does not (I am running MX18.3 with the latest flatpak as of this moment).

I googled around and see instructions like this https://www.linuxquestions.org/questions/showthread.php?p=6048208

but running this command for me seems to do nothing:

env PULSE_SERVER=unix:/tmp/pulse-PKdhtXMmr18n/native flatpak run org.kde.dolphin

Video files seem to play, but still no sound in those or in Mp3s.

Could you point me in the right direction?

thanks!

**Comment by Siosm** [comment]
You will probably need to add `--socket=pulseaudio` to the finish-args to enable access to pulseaudio.

**Comment by Siosm** [comment]
You should be able to test that with the current flatpak by manually adding the permission on the command line or via https://flathub.org/apps/details/com.github.tchx84.Flatseal

**Comment by freecicero** [comment]
That worked great!  Thank you very much!

**Comment by freecicero** [comment]
Thanks again!

**Comment by Siosm** [comment]
Re-opening this to make sure we work on it at some point.

**Comment by travier** [comment]
Fixed with #78
