### ISSUE TITLE
[Question] How does dolphin's flatpak create, delete and execute program if flatpak's can't do so?

### ISSUE THREAD

**Issue by prateekmedia** [flathub/org.kde.dolphin#51]
Taken from https://github.com/flathub/flathub/issues/2513#issue-999609610

Hi, 
I know it might not be the right place to ask this but can you tell me how can dolphin create, delete and execute files and folder's if flatpak's are restricted to not do so by default?

Here is the [flatpak manifest](https://github.com/flathub/org.kde.dolphin/blob/master/org.kde.dolphin.json).

I wanted to know this cause I was stuck in a flatpak program where I can't execute program I needed to within from the app and create the folder if it doesn't exist.

**Comment by prateekmedia** [comment]
cc @grulja, @tsdgeos If any one of you know about this, please tell me.

**Comment by grulja** [comment]
You can see that we have `--filesystem=home` permission in our manifest. This gives Dolphin access to files in user's home directory.

**Comment by prateekmedia** [comment]
Thanks @grulja, I will look into it.
