### ISSUE TITLE
Unable to edit File Type Options for file/folder properties

### ISSUE THREAD

**Issue by WineBottles** [flathub/org.kde.dolphin#57]
I originally made this  ticket 3 weeks ago on bugs.kde.org and was now notified to make a ticket here instead.

"It's not really a Dolphin bug, but the way containerized applications lock themself out of the rest of the system. This is arguably a packaging bug, since a file manager that doesn't have full access to the filesystem is less than useful as a file manager. **You should ask the Dolphin Flatpak packagers to allow the app full access to the filesystem by default in their packaging**, because, that's kind of like the whole point of a file manager. :)"

Original bug ticket:

Dolphin Flatpak unable to edit File Type Options for file properties. I have tried allowing all permissions in Flatseal and that did not produce a different result.

STEPS TO REPRODUCE
1. Open dolphin
2. Right click on any file type OR FOLDER (.ods, .png, folder, etc)
3. Click on the File Type Options button under Type

OBSERVED RESULT
An message box pops up with Could not start the "keditfiletype5" executable, please check your installation.

EXPECTED RESULT
Being able to edit file type options when that button is clicked.

SOFTWARE/OS VERSIONS
OS: Arch Linux x86_64
Kernel: 5.14.16-arch1-1
(available in About System)
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.2
Graphics Platform: X11

Dolphin flatpak version: 21.08.3
Flatpak version: flatpak 1.12.2-1
Flatseal version: 1.7.4

**Comment by travier** [comment]
Looks like we are missing `keditfiletype5` from `kde-cli-tools`. I don't know if this should be part of the runtime or this Flatpak but we can start by adding it here.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
http://user-images.githubusercontent.com/42837531/141826026-d4f8201a-efa8-46e2-90ab-4d68096772b6.png

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Are "http://github.com/flathub/org.kde.dolphin/issues/13" and "http://github.com/flathub/org.kde.dolphin/issues/57" duplicate?

**Comment by Derb1958** [comment]
Excellent, thank you for the advice.

**Comment by RacerBG** [comment]
I'm getting a slightly different error message: "Could not find the "keditfiletype5" executable in PATH."

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/org.kde.dolphin/issues/57#issuecomment-1864277794

@RacerBG, that's probably just an upstream phrasal modification, because https://github.com/flathub/org.kde.dolphin/issues/57#issuecomment-969137459 refers to `$PATH` inherently anyway. After all, if the binary isn't in the current working directory, `$PATH` is checked next.
