### ISSUE TITLE
The current version of "org.kde.dolphin" is more old than the most new version of "dolphin".

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/org.kde.dolphin#60]
The current version of http://github.com/flathub/org.kde.dolphin is "21.08.3", whereas the most new version of "dolphin" is "21.11.80".

**Comment by tsdgeos** [comment]
No

**Comment by travier** [comment]
`*.80` versions are beta / un-released versions.
