### ISSUE TITLE
Unable to access external filesystems on Debian-based distributions

### ISSUE THREAD

**Issue by esjarc** [flathub/org.kde.dolphin#61]
It is not possible to access external filesystems (such as optical disks, USB drives or virtual machine shared folders) on Debian-/Ubuntu-based systems, as the permission to access `/media` is not declared in the manifest.

Therefore I suggest adding `"--filesystem=/media"` to [`org.kde.dolphin.json`](https://github.com/flathub/org.kde.dolphin/blob/master/org.kde.dolphin.json).

Are there any reasons (e. g. security concerns) why permissions are only granted to `/run/media` and not `/media` at the moment?

**Steps to reproduce:**
- open Dolphin on any supported Debian-based distribution
- mount any external device
- try accessing the device by selecting it in Dolphin's sidebar

**Expected result:**
Ability to browse and edit the contents on the external device.

**Actual result:**
Error message: "The file or folder /media/x/y does not exist."

**Workaround:**
`flatpak override --filesystem=/media org.kde.dolphin`

**Verified with the following software versions:**
OS: Kubuntu 18.04, 20.04 and 22.04
Dolphin flatpak version: 21.08.3
Flatpak version: 1.12.2-1 ([Flatpak stable PPA](https://launchpad.net/~flatpak/+archive/ubuntu/stable))

**Comment by tsdgeos** [comment]
Can you try if installing

flatpak install --user https://dl.flathub.org/build-repo/65553/org.kde.dolphin.flatpakref

makes it work for you?

**Comment by esjarc** [comment]
@tsdgeos Thank you, your patch fixes this issue! I am able to read from a CD and I am able to read/write/delete folders and files on an USB thumb drive (tested on Kubuntu 22.04).
```
flatpak info --show-permissions org.kde.dolphin
[Context]
shared=network;ipc;
sockets=x11;wayland;
devices=dri;
filesystems=home;/media;xdg-config/kdeglobals:ro;/run/media;

[Session Bus Policy]
com.canonical.AppMenu.Registrar=talk
org.kde.kiod5=talk
org.kde.kpasswdserver=talk
org.kde.JobViewServer=talk

[System Bus Policy]
org.freedesktop.UDisks2=talk
```

I guess the issue can be closed then (once you merged the patch)?

**Comment by tsdgeos** [comment]
Thanks for testing

**Comment by travier** [comment]
Please open a new issues with as much info as possible (that includes links to other similar issues) instead of commenting on a closed issue.
