### ISSUE TITLE
SMB protocol is not working

### ISSUE THREAD

**Issue by Githob2021** [flathub/org.kde.dolphin#66]
As the title states, my Dolphin flatpak SMB protocol is not working. All it says is "Invalid protocol." in a big red banner at the top when trying to connect to a Windows share.

This page https://wiki.manjaro.org/index.php?title=Using_Samba_in_your_File_Manager for Dolphin you don't need anything extra but you may need gvfs-smb package.

I don't have gvfs-smb installed on my system, would that matter regardless if I am using the flatpak? Shouldn't it be included in the Dolphin flatpak?

Edit: I installed the gvfs-smb and dependency packages and it's still the same. I think this is a bug/missing package issue for the flatpak.

**Comment by tsdgeos** [comment]
Why would dolphin need gvfs-smb? gvfs-smb is for gnome stuff only

**Comment by tsdgeos** [comment]
For samba to work we need [at least] to package samba client libraries.

**Comment by tsdgeos** [comment]
Trying to fix it in https://github.com/flathub/org.kde.dolphin/pull/67

**Comment by tsdgeos** [comment]
I don't have a smb setup at hand, can you try if installing the potentially fixed dolphin

flatpak install --user https://dl.flathub.org/build-repo/69984/org.kde.dolphin.flatpakref

Makes it work for you?

**Comment by Githob2021** [comment]
> I don't have a smb setup at hand, can you try if installing the potentially fixed dolphin
> 
> flatpak install --user https://dl.flathub.org/build-repo/69984/org.kde.dolphin.flatpakref
> 
> Makes it work for you?

Thanks! I no longer get the "Invalid protocol." red banner anymore.

I am now able to connect to my Windows 10 computer, but the Windows 7 one which should be set up the exact same way produces this error:

"Internal Error
Please send a full bug report at https://bugs.kde.org
Unknown error condition: [8216] Unknown error 8216"

**Comment by Githob2021** [comment]
This should also fix issue 7.

https://github.com/flathub/org.kde.dolphin/issues/7
