### ISSUE TITLE
Can't access network shares

### ISSUE THREAD

**Issue by MasterJubei** [flathub/org.kde.dolphin#7]
I can't access Windows network shares, smb://ip just says "Invalid Protocol"

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Is this issue specifically for SAMBA?  Dolphin is appearing support discovery of MTP shares for me, although I have not configured any.

http://user-images.githubusercontent.com/42837531/141826771-a714abd1-c632-41d5-86f6-b0af029e54ed.png

**Comment by travier** [comment]
MTP is for local media devices. We might be missing some KIO module for network shares.

**Comment by Githob2021** [comment]
This issue seems to be fixed in issue 66.

https://github.com/flathub/org.kde.dolphin/issues/66
