### ISSUE TITLE
Not showing video thumbnails by default

### ISSUE THREAD

**Issue by Harnapazade** [flathub/org.kde.dolphin#70]
Dolphin flatpak needs ffmpegthumbs package by default so that we can see video thumbnails without a problem. Thanks....

**Comment by oshanz** [comment]
@Harnapazade, how can I install that package? I couldn't find it on flathub

**Comment by travier** [comment]
This might need to be provided in the Flatpak like we do for kdenlive.

**Comment by Harnapazade** [comment]
We need 2 package basically. 

**ffmpegthumbs, kffmpegthumbnailer**

**Comment by itsnotsaved** [comment]
#95

**Comment by itsnotsaved** [comment]
> We need 2 package basically. 
> **ffmpegthumbs, kffmpegthumbnailer**

**kdegraphics-thumbnailers** also, list of packages that install with dolphin on ubuntu systems

baloo-kf5, ffmpegthumbs, kdegraphics-thumbnailers, kimageformat-plugins https://github.com/flathub/org.kde.dolphin/issues/69 https://github.com/flathub/org.kde.gwenview/issues/30, kuserfeedback-doc, libavif13, libdolphinvcs5, libgav1-0, libkf5attica5, libkf5auth5, libkf5baloowidgets-bin, libkf5baloowidgets-data, libkf5baloowidgets5, libkf5kcmutils-data, libkf5kcmutils5, libkf5kexiv2-15.0.0, libkf5newstuff-data, libkf5newstuff5, libkf5newstuffcore5, libkf5syndication5abi1, libkuserfeedbackcore1, libkuserfeedbackwidgets1, libpackagekitqt5-1, libyuv0, qml-module-org-kde-newstuff, qml-module-org-kde-userfeedback

**Comment by travier** [comment]
This is a free / open source software project. Issues get fixed when contributors choose to invest time on them. If you want an issue fixed sooner you can either contribute directly to fix it or sponsor someone else to do it for you.

**Comment by Justinzobel** [comment]
Fixed by #268
