### ISSUE TITLE
Window contents display area remains white

### ISSUE THREAD

**Issue by itsnotsaved** [flathub/org.kde.dolphin#95]
I have installed kvantum 1.0.4 on ubuntu 22.04.01 and dark theme works with other apps. e.g. ksnip (snap), kdenlive (flatpak - i didn't test if it use own dark theme)

If i installed dolphin using apt then dark theme works well for it (kvantum)
![ksnip_20220926-190504](https://user-images.githubusercontent.com/73447325/192271153-2d531e68-75ba-485e-9f87-b283015cc3be.png)

But doesn't work well with flatpak
![ksnip_20220926-183540](https://user-images.githubusercontent.com/73447325/192270067-944caf1a-ff8b-4223-a036-b48a56ad7be8.png)

**Comment by itsnotsaved** [comment]
#70

**Comment by travier** [comment]
Issues with themes are not issues in the app. You should make sure the team has a Flatpak version.

**Comment by itsnotsaved** [comment]
>You should make sure the team has a Flatpak version.

I don't understand.

>Issues with themes are not issues in the app.

I know dolphin software doesn't have a problem. But this flatpak app (dolphin) doesn't become dark completely same as apt dolphin. If i set light through kvantum manager and relaunch dolphin (apt) then it become light and if i set dark and relaunch then become dark.

Or do you know any alternative way to make this flatpak dolphin completely dark?

**Comment by travier** [comment]
Sorry, I meant "theme" in the comment, not "team".

**Comment by travier** [comment]
Flatpak Apps usually need their own instance of a theme so you would have to look for a Flatpak version of the theme that you want to use.

**Comment by itsnotsaved** [comment]
I tried past two days but no luck (white area remains or no style change)

Installed themes related packages
org.gtk.Gtk3theme.Arc-Dark
org.gtk.Gtk3theme.Yaru-dark (also system)
org.kde.KStyle.Adwaita
org.kde.KStyle.Kvantum
org.kde.PlatformTheme.QGnomePlatform

ubuntu 22.04.01 | x11

**Comment by outusuke** [comment]
Is there a way to make Dolphin follow the system theme? Other Flatpak KDE applications adjust to the system theme automatically, but Dolphin continues to use a white color theme despite the system settings.

**Comment by outusuke** [comment]
Is there a way to enable dark mode? I've tried installing org.gtk.Gtk3theme.Breeze-Dark and setting the GTK_THEME environment variable to Breeze-Dark, but it didn't work as expected. Any suggestions?

![Screenshot from 2024-09-15 12-09-26](https://github.com/user-attachments/assets/3dade487-4cf8-436f-a152-6b053a43ef38)
